### ISSUE TITLE
Can't start application

### ISSUE THREAD

**Issue by sevenzing** [innonymous/compose#1]
After starting application via

`docker-compose up`

I got the following error:

```
api-server_1  | [2021-09-22 14:12:10 +0000] [10] [ERROR] Exception in worker process
api-server_1  | Traceback (most recent call last):
api-server_1  |   File "/app/env/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
api-server_1  |     worker.init_process()
api-server_1  |   File "/app/env/lib/python3.9/site-packages/uvicorn/workers.py", line 66, in init_process
api-server_1  |     super(UvicornWorker, self).init_process()
api-server_1  |   File "/app/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
api-server_1  |     self.load_wsgi()
api-server_1  |   File "/app/env/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
api-server_1  |     self.wsgi = self.app.wsgi()
api-server_1  |   File "/app/env/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
api-server_1  |     self.callable = self.load()
api-server_1  |   File "/app/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
api-server_1  |     return self.load_wsgiapp()
api-server_1  |   File "/app/env/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
api-server_1  |     return util.import_app(self.app_uri)
api-server_1  |   File "/app/env/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
api-server_1  |     mod = importlib.import_module(module)
api-server_1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
api-server_1  |     return _bootstrap._gcd_import(name[level:], package, level)
api-server_1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
api-server_1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
api-server_1  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
api-server_1  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
api-server_1  |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
api-server_1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
api-server_1  |   File "/app/innonymous/api/__init__.py", line 26, in <module>
api-server_1  |     settings = APISettings()
api-server_1  |   File "pydantic/env_settings.py", line 36, in pydantic.env_settings.BaseSettings.__init__
api-server_1  |   File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
api-server_1  | pydantic.error_wrappers.ValidationError: 1 validation error for APISettings
api-server_1  | key
api-server_1  |   Key should be at least 32 bytes long. (type=value_error)
```

**Comment by sevenzing** [comment]
The thing is that `API_KEY` you should provide in `.env` file should be at least 32 char long. We will add this requirement in README
